version: "3.9"
services:
  challenge:
    build: .
    image: challenge
    container_name: challenge
    ports:
      - 3333:3333
    volumes:
      - ./videos:/app/videos
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
